### ISSUE TITLE
[Bug] Openrss blocking freshrss for too many simultaneous requests

### ISSUE THREAD

**Issue by materemias** [FreshRSS/FreshRSS#6973]
### Describe the bug

according to [issue 163](https://openrss.org/issue/163) there is a problem because FreshRSS tries to pull all sources at the same time.
Please check [their guidelines](https://openrss.org/guides/developers-guide-to-open-rss-feeds) and see how the fetching could be improved.

### To Reproduce

Subscribe to multiple OpenRSS feeds

### Expected behavior

Requests towards the same source should be [spaced out](https://openrss.org/guides/developers-guide-to-open-rss-feeds#space-out-your-requests).

### FreshRSS version

1.24.3

**Comment by Frenzie** [comment]
Unlike the recommended picture which shows some degree of parallelism (included below), requests are completely sequential. So it's unclear if there's anything actionable here. 

![image](https://github.com/user-attachments/assets/21369328-187b-4226-b606-e90af995e309)

**Comment by materemias** [comment]
Thanks a lot for your quick answer, I think they don't require the requests to only follow each other but to have eg 1-2 sec of space in between (the sample image is misleading with the overlapping timings)
so eg even if the first request finishes in ~200ms the next should not start until additional ~1800ms passed. Does FreshRSS do this?
![image](https://github.com/user-attachments/assets/a6eb5c70-ae80-4e17-ab98-092f7aed3b9b)

**Comment by Alkarex** [comment]
Probably a user refreshing feeds from the Web interface instead of by cron job.
While the cron job fetches feeds sequentially, the manual refresh from the Web UI performs up to 10 request in parallel. This can be tweaked in the configuration on the model of:

https://github.com/FreshRSS/FreshRSS/blob/e9ce099277bd5cb0257b9535cfaed42d87670b88/config.default.php#L93-L95

**Comment by flashy4190** [comment]
Hello,

This appears to still be an issue even with `'nb_parallel_refresh' => 1` set. I am not manually refreshing feeds from the web UI; I am letting them automatically refresh via the cron job using the timing given in the example Docker Compose setup (`CRON_MIN: 2,32`).

I have around 30 feeds from OpenRSS configured in FreshRSS. They were all working fine around one month ago; now all of them no longer receive new articles.

It appears that frequent requests from a FreshRSS server cause the source IP address to get banned from OpenRSS. As an example: This morning, I was able to load a new feed from openrss.org in a web browser. Trying to then add this new feed to my FreshRSS installation returned a 429 response according to FreshRSS logs. I tried a few attempts, even including `#force_feed`, each attempt spaced a few seconds apart, all to no avail. I then found that I was no longer able to load openrss.org in the same web browser, suggesting that I've been IP banned.

I have changed the automatic refresh time of each of my OpenRSS feeds from default to one month to essentially stop them from refreshing and prevent getting IP-banned while I troubleshoot the problem further.

FreshRSS satisfies all of my RSS reader requirements aside from this, and I unfortunately only found out about this problem **after** I had set up all of my other feeds and was happily using it daily. This appears to be difficult to troubleshoot as an end-user as sending only a few requests from FreshRSS to OpenRSS appears to result in a ban.

Please let me know how I can help contribute to a potential solution to this problem.

**Comment by flashy4190** [comment]
Hello,

I've been in contact with an OpenRSS engineer over the last few days. Below is a direct quote that describes the biggest problem they're currently experiencing with FreshRSS. It also appears that OpenRSS feeds no longer work in FreshRSS due to this reason and a few more (see below).

>I've taken a closer look and see the requests coming in from FreshRSS. But unfortunately the requests may either be automatically banned again, or the feed requests will never have updates until the FreshRSS issues are resolved.
>
>The biggest issue right now is that FreshRSS isn't respecting the max-age value in the Cache-Control header in our responses. FreshRSS needs to wait until that time elapses before making a subsequent request to a feed. You can read more about this under the [Wait until Cache-Control expires](https://openrss.org/guides/developers-guide-to-open-rss-feeds#wait-until-cachecontrol-expires) section of our Developer's Guide.

[This page](https://openrss.org/app/freshrss) describes the problems OpenRSS has identified with FreshRSS. There are currently four, with the two most severe being "Using multiple networks to request feeds too frequently" and "Requesting many feeds too quickly."

What would be a starting point to work on the max-age problem?

**Comment by Frenzie** [comment]
> What would be a starting point to work on the max-age problem?

To find out the actual value using cURL or browser devtools. The sample value in the linked documentation is `300`, which is much too low to even be relevant regardless if it is or isn't respected. In any case I believe it's supported by the feed cache.

**Comment by Alkarex** [comment]
@flashy4190 Thanks for following up

> The biggest issue right now is that FreshRSS isn't respecting the max-age value in the Cache-Control header in our responses. 

We do obey `Cache-Control: max-age` (since FreshRSS 1.25.0, December 2024), but note that this only affects a single feed from a given FreshRSS instance and does not say anything about multiple feeds or multiple instances.

The page https://openrss.org/app/freshrss contains several basic misconceptions. It is probably made by some kind of bogus automated tool.
* *This application is requesting feeds multiple times using different networks*. Obviously, as FreshRSS is deployed and operated by various users on various servers. If OpenRSS performs some filtering based on HTTP user-agent, they are wrong and this contributes to breaking the Web. It is the same as to say: *The application Chrome is requesting multiple Web pages using different networks* 🤦🏻‍♂️
    * *The application should fix this behavior as soon as possible by restricting its requests to one IP address and network per feed request at a time.* => Bogus suggestion.
    * Meanwhile, for you as a user, you can override the User-Agent to an empty string or random string for those OpenRSS feeds. Not a good practice, but needed for bad servers.
* *Failing to slow down its requests*. They are mixing concepts between a single feed vs. multiple feeds, and single instance vs. multiple instances.
    * It is normally not a problem for feeds that have an appropriate HTTP cache policy and support for HTTP conditional requests and/or WebSub.
    * There is nevertheless a [FreshRSS *Rate Limiter* extension](https://github.com/pe1uca/xExtension-RateLimiter/) for users requesting many feeds from a picky server, which seems to be your case.
* *Not declaring that it accepts feed content*. Of course we do. Bogus. This might be a sign of misunderstanding of the fact that there different types of requests involved, with different types of `Accept`, for instance when accessing a favicon or requesting a Web page.

Furthermore, testing on https://openrss.org/rss , OpenRSS seems to fail to support standard HTTP conditional requests (`HTTP 304 Not Modified`), which would be a good start... OpenRSS also apparently does not support WebSub, which would be a great improvement, as this would completely alleviate those issues by switching to a push instead of pull method.

I would happily have a dialogue with someone from OpenRSS. You are welcome to direct them here or by e-mail.

**Comment by flashy4190** [comment]
I have asked the OpenRSS engineer I've been communicating with if they and/or someone else from their team would be willing to discuss further directly with you, @Alkarex, via this issue or some other method.

Thanks for everyone's input on this issue.

**Comment by flashy4190** [comment]
I've received confirmation for further discussion. Sounds like they prefer email. I'll send the details to the email address I found on the website linked to in your bio, @Alkarex.

**Comment by trekzavier** [comment]
i contacted open rss about this. They working on tool and gave me a link to test the requests freshrss is making and outputs all the errors. go to test.openrss.org and it will give you a test link.
i'm using it on my freshrss instance and its showing that freshrss has many issues

**Comment by Frenzie** [comment]
It doesn't work. Apparently html.js is quite important to its functionality and that returns a 404.

**Comment by Alkarex** [comment]
@trekzavier I have had a long e-mail conversation in July with one engineer at OpenRSS, which did not go so well.
The current version of FreshRSS (1.27.0) has implemented all the relevant standards, which is not the case for OpenRSS, which wrongly assumes FreshRSS is a central service (claiming that we use distributed IPs...), does not correctly implement HTTP conditional requests, misunderstand and does not correctly implement Retry-After, does not implement WebSub, misinterpret their logs, and uses bad practices such as filtering requests based on user-agent. I have also offered a controlled test, which they declined.

Now I am very much open to make any technical improvement, but the current situation is that I cannot take them seriously based on all the wrong claims they make (their [status page](https://openrss.org/app/freshrss) is complete garbage) and the e-mail responses they gave. I will not spend more time myself on them for now.

So it is nice if you would like to help, and you are much welcome. What I need are some concrete suggestions, filtered by someone who understand how the Web and its standards work.

**Comment by Frenzie** [comment]
> wrongly assumes FreshRSS is a central service (claiming that we use distributed IPs...

I get the impression most of the claims automatically follow from this odd assumption. (One wonders what they think of e.g. Vivaldi or QuiteRSS…) I can't say I understand what it's trying to claim about the `Accept` header or requesting content from the wrong location though. Or perhaps requesting a favicon is responsible for both… blame Microsoft for that one.

**Comment by goestav** [comment]
The page for FreshRSS has been [updated](https://openrss.org/app/freshrss) ([archived page](https://web.archive.org/web/20260328134820/https://openrss.org/app/freshrss) for those that have been blocked), the severe issues have been resolved and two "critical issues" remain.
Would it be possible to reopen this issue?

**Comment by Frenzie** [comment]
Neither of those sound plausible imho. Especially the second, since `<link rel="alternate" type="application/rss+xml" …>` (or atom) is where the program gets a feed from unless it's a direct link… 

The first sounds like little more than a rephrasing of the former excessive feed requests complaint.

robots.txt might be true, I'd have to check, but ensure the non-robot user can't access a link disallowed in robots.txt sounds conceptually suspicious to my ears. Much like saying Chrome or Firefox shouldn't access a link because it's disallowed in robots.txt, to reuse an earlier analogy. [Edit: to be more precise, it's accessing an API, not crawling a website.]

<img width="60%" alt="Image" src="https://github.com/user-attachments/assets/669cac53-1504-4363-8db2-a1a8082a270f" />
